### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by RohanTalip** [RohanTalip/VectorDrawable2Svg#1]
I created an issue on the upstream repository asking about a licence/license:
https://gitlab.com/Hyperion777/VectorDrawable2Svg/issues/3

**Comment by RohanTalip** [comment]
An MIT license file seems appropriate.

@Hyperion777 , I'm hoping you are the same person as on gitlab.com ... what do you think?

**Comment by AlessandroLucchet** [comment]
Yes, a MIT license it's ok.
I added to the initial repo.
Good work! 👍

**Comment by RohanTalip** [comment]
Thanks @Hyperion777 !
