### ISSUE TITLE
output svg has the wrong color when an alpha channel is specified in a fillColor in the input

### ISSUE THREAD

**Issue by bs111** [RohanTalip/VectorDrawable2Svg#2]
I have a xml Vector file .

[ic_launcher_foreground.zip](https://github.com/RohanTalip/VectorDrawable2Svg/files/3668704/ic_launcher_foreground.zip)

1. Import it to https://shapeshifter.design, have a preview :
![image](https://user-images.githubusercontent.com/38519076/65847423-0caebb00-e374-11e9-9419-feb086bbfb42.png)

2.use the python python VectorDrawable2Svg.py ic_launcher_foreground.xml。to see the result by chrome.
![image](https://user-images.githubusercontent.com/38519076/65847464-3f58b380-e374-11e9-8d03-228e095de7de.png)

**Comment by RohanTalip** [comment]
@bs111 , thanks for the bug report.  I think this should be fixed now, at least for your example input.

**Comment by bs111** [comment]
OK,thanks.
